name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: '15'

      - name: Install
        run: npm install

      - name: lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
